FROM golang:alpine AS builder
WORKDIR /app
ENV GOWORK=off
COPY go.mod go.sum* ./
RUN go mod download
COPY ./ ./
RUN CGO_ENABLED=0 GOOS=linux GOMEMLIMIT=500MiB GOGC=20 go build -p 1 -o qisur-tracker cmd/tracker/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/qisur-tracker .
EXPOSE 8087
CMD ["./qisur-tracker"]
