# Pre-compiled lightweight image
FROM alpine:3.19
WORKDIR /app

# Copy the pre-compiled binary
COPY deploy-bins/qisur-tracker .

# Expose the default listening port
EXPOSE 8087

# Execute the microservice
CMD ["./qisur-tracker"]
