FROM golang:alpine AS builder
WORKDIR /app
ENV GOWORK=off
COPY go.mod go.sum* ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download
COPY ./ ./
RUN --mount=type=cache,target=/root/.cache/go-build \
    --mount=type=cache,target=/go/pkg/mod \
    CGO_ENABLED=0 GOOS=linux GOMEMLIMIT=500MiB GOGC=20 go build -o qisur-tracker cmd/tracker/main.go

FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/qisur-tracker .
EXPOSE 8087
CMD ["./qisur-tracker"]
